---
title: "DSBox_DCBike"
author: "Jenna Keute"
date: "10/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

The data include daily bike rental counts (by members and casual users) of Capital Bikeshare in Washington, DC in 2011 and 2012 as well as weather information on these days. The data is contained in the dsbox package and is called dcbikeshare.

The original data sources are http://capitalbikeshare.com/system-data and http://www.freemeteo.com.

The codebook is below:

Variable name	Description
instant	record index
dteday	date
season	season (1:winter, 2:spring, 3:summer, 4:fall)
yr	year (0: 2011, 1:2012)
mnth	month (1 to 12)
holiday	whether day is holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)
weekday	day of the week
workingday	if day is neither weekend nor holiday is 1, otherwise is 0.
weathersit	1: Clear, Few clouds, Partly cloudy, Partly cloudy
2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
temp	Normalized temperature in Celsius. The values are divided by 41 (max)
atemp	Normalized feeling temperature in Celsius. The values are divided by 50 (max)
hum	Normalized humidity. The values are divided by 100 (max)
windspeed	Normalized wind speed. The values are divided by 67 (max)
casual	Count of casual users
registered	Count of registered users
cnt	Count of total rental bikes including both casual and registered

## Recoding data

### Recode season

Recode the season variable to be a factor with meaningful level names as outlined in the codebook, with spring as the baseline level.

<!-- ```{r} -->
<!-- dcbikeshare <- ___ %>% -->
<!--   ___( -->
<!--     season = ___( -->
<!--     ___ -->
<!--     ), -->
<!-- ``` -->


<!-- ```{r} -->
<!-- season = ___(___) -->
<!--   ) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- dcbikeshare <- dcbikeshare %>% -->
<!--   mutate( -->
<!--     season = case_when( -->
<!--       season == 1 ~ "winter", -->
<!--       season == 2 ~ "spring", -->
<!--       season == 3 ~ "summer", -->
<!--       season == 4 ~ "fall" -->
<!--     ), -->
<!--     season = fct_relevel(season, "spring", "summer", "fall", "winter") -->
<!--   ) -->
<!-- ``` -->

### Recode holiday and workingday

Recode the binary variables holiday and workingday to be factors with levels no (0) and yes (1), with no as the baseline level.

<!-- ```{r} -->
<!-- dcbikeshare <- ___ %>% -->
<!--   ___( -->
<!--     ___ -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- dcbikeshare <- dcbikeshare %>% -->
<!--   mutate( -->
<!--     holiday = ifelse(holiday == 0, "no", "yes"),       -->
<!--     holiday = fct_relevel(holiday, "no", "yes"),     -->
<!--     workingday = ifelse(workingday == 0, "no", "yes"), -->
<!--     workingday = fct_relevel(workingday, "no", "yes") -->
<!--   ) -->
<!-- ``` -->

### Recode year

Recode the yr variable to be a factor with levels 2011 and 2012, with 2011 as the baseline level.

<!-- ```{r} -->
<!-- dcbikeshare <- ___ %>% -->
<!--   ___( -->
<!--     ___ -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- dcbikeshare <- dcbikeshare %>% -->
<!--   mutate( -->
<!--     yr = ifelse(yr == 0, "2011", "2012"), -->
<!--     yr = fct_relevel(yr, "2011", "2012") -->
<!--   ) -->
<!-- ``` -->
### Recode weathersit

Recode the weathersit variable as 1 - clear, 2 - mist, 3 - light precipitation, and 4 - heavy precipitation, with clear as the baseline.

<!-- ```{r} -->
<!-- dcbikeshare <- ___ %>% -->
<!--   ___( -->
<!--     ___ -->
<!--     ), -->
<!--     ___ -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- dcbikeshare <- dcbikeshare %>% -->
<!--   mutate( -->
<!--     weathersit = case_when( -->
<!--       weathersit == 1 ~ "clear", -->
<!--       weathersit == 2 ~ "mist", -->
<!--       weathersit == 3 ~ "light precipitation", -->
<!--       weathersit == 4 ~ "heavy precipitation" -->
<!--     ), -->
<!--     weathersit = fct_relevel(weathersit, "clear", "mist", "light precipitation", "heavy precipitation") -->
<!--   ) -->
<!-- ``` -->
### Recoding warning
At this point, you might wonder what this warning means:

`Warning: Unknown levels in `f`: heavy precipitation`
This is simply R warning us that while it is possible for the weathersit variable to have the value 4 for heavy precipitation, this never actually occurs in the data. Consequently, the weathersit factor only has three levels.

### Creating new variables

Create raw values for temperature, humidity, and windspeed

Calculate raw temperature, feeling temperature, humidity, and windspeed as their values given in the dataset multiplied by the maximum raw values stated in the codebook for each variable. Instead of writing over the existing variables, create new ones called temperature_raw, feeling_temperature_raw, humidity_raw, windspeed_raw.

<!-- ```{r} -->
<!-- dcbikeshare <- ___ %>% -->
<!--   ___( -->
<!--     ___ -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- dcbikeshare <- dcbikeshare %>% -->
<!--   mutate( -->
<!--     temperature_raw = temp * 41, -->
<!--     feeling_temperature_raw = atemp * 50, -->
<!--     humidity_raw = hum * 100, -->
<!--     windspeed_raw = windspeed * 67 -->
<!--   ) -->
<!-- ``` -->

### Check cnt variable

Check that the sum of casual and registered adds up to cnt for each record. Do this by creating a new column that takes on the value TRUE if they add up and FALSE if not, and then checking if all values in that column are TRUEs.

<!-- ```{r} -->
<!-- ___ %>% -->
<!--   ___(cas_plus_reg = ___) %>% -->
<!--   ___(all_zero = __(___ == ___)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- dcbikeshare %>% -->
<!--   mutate(cas_plus_reg = casual + registered) %>% -->
<!--   summarise(all_zero = all(cas_plus_reg == cnt)) -->
<!-- ``` -->

### Bike rentals and temperature

### Recreating this visualization

<!-- ```{r} -->
<!-- dcbikeshare %>% -->
<!--   ggplot(___) + -->
<!--     geom____(___) + -->
<!--     ___( -->
<!--       title = ___, -->
<!--       subtitle = ___, -->
<!--       x = ___, -->
<!--       y = ___, -->
<!--       color = ___ -->
<!--     ) + -->
<!--   ___ -->
<!-- ``` -->

<!-- ```{r} -->
<!-- dcbikeshare %>% -->
<!--   ggplot(mapping = aes(x = dteday, y = cnt, color = feeling_temperature_raw)) + -->
<!--     geom_point(alpha = 0.7) + -->
<!--     labs( -->
<!--       title = "Bike rentals in DC, 2011 and 2012", -->
<!--       subtitle = "Warmer temperatures associated with more bike rentals", -->
<!--       x = "Date", -->
<!--       y = "Bike rentals", -->
<!--       color = "Temperature (C)" -->
<!--     ) + -->
<!--   theme_minimal() -->
<!-- ``` -->
### Bike rentals vs temperature

Fit a linear model predicting total daily bike rentals from raw daily temperature and answer the questions below.

<!-- ```{r} -->
<!-- cnt_tmp <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- cnt_tmp %>% -->
<!--   ___ -->
<!-- ``` -->
<!-- ```{r} -->
<!-- cnt_tmp <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(cnt ~ temperature_raw, data = dcbikeshare) -->
<!-- cnt_tmp %>% -->
<!--   tidy() -->
<!-- ``` -->
Now, based on your findings, answer the following question.

Which interpretations are correct?

The slope of the model is approximately 1215, which means that, for each additional degree celsius, we can expect bike rentals to increase by 1215.
The model has the intercept at approximately 1215, which means that at a day with a temperature of 0 degrees celsius, we can except to have, on average, 1215 bike rentals.
The model has the intercept at approximately 162, which means that at a day with a temperature of 0 degrees celsius, we can except to have, on average, 162 bike rentals.
The slope of the model is approximately 162, which means that, for each additional degree celsius, we can expect bike rentals to increase by 162.

A: The correct answers are that the intercept is at approximately 1215 with a slope of approximately 162.

Use the chunk below to print out the R2 of the model.

<!-- ```{r} -->
<!-- glance(___)$___ -->
<!-- ``` -->

<!-- ```{r} -->
<!-- glance(cnt_tmp)$r.squared -->
<!-- ``` -->
[1] 0.3937487

Now, answer the following question:

What does the R-squared mean in this context?
39.4% of the variability in the number of total daily bike rental is explained by temperature.
On average, the number of bike rentals predicted squared by the model differs from the actual number of bike rentals squared by 39.4%
The model predicts the correct number of bike rentals 39.4% of the time
On average, the number of bike rentals predicted by the model differs from the actual number of bike rentals by 39.4%

A: 39.4% of the variability in the number of total daily bike rental is explained by temperature. 

### Bike rentals vs feeling 

Fit another linear model predicting total daily bike rentals from raw daily feeling temperature. Then, proceed to answering the questions below.

<!-- ```{r} -->
<!-- cnt_atmp <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(cnt ~ feeling_temperature_raw, data = dcbikeshare) -->
<!-- ___ %>% -->
<!--   ___ -->
<!-- ``` -->
<!-- ```{r} -->
<!-- cnt_atmp <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(cnt ~ feeling_temperature_raw, data = dcbikeshare) -->
<!-- cnt_atmp %>% -->
<!--   tidy()cnt_atmp <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(cnt ~ feeling_temperature_raw, data = dcbikeshare) -->
<!-- cnt_atmp %>% -->
<!--   tidy() -->
<!-- ``` -->
Which interpretations are correct?

The model has the intercept at approximately 946, which means that at a day with an apparent temperature of 0 degrees celsius, we can except to have, on average, 946 bike rentals. ✓
The slope of the model is approximately 946, which means that, for each additional degree in apparent temperature, we can expect bike rentals to increase by 946. ✗
The slope of the model is approximately 150, which means that, for each additional degree in apparent temperature, we can expect bike rentals to increase by 150. ✓
The model has the intercept at approximately 150, which means that at a day with an apparent temperature of 0 degrees celsius, we can except to have, on average, 150 bike rentals. ✗


Use the chunk below to print out the R2 of the model.

<!-- ```{r} -->
<!-- glance(___)$___ -->
<!-- ``` -->

<!-- ```{r} -->
<!-- glance(cnt_atmp)$r.squared -->
<!-- ``` -->

[1] 0.3982439

Is the following statement true or false?

39.8% of the variability in the number of total daily bike rentals is explained by apparent temperature.
False ✗
True ✓

Now, based on your findings from the two questions above, answer the following:

Which is the better explanatory variable of bike rentals?
Feeling temperature is the better predictor, since the R-squared is slightly lower. ✗
Absolute temperature is a better predictor, because the R-squared is higher. ✗
Feeling temperature is the better predictor, since the R-squared is slightly higher. ✓
Absolute temperature is a worse predictor, since the R-squared is higher. ✗

## Full model

Fit a model predicting total daily bike rentals from season, year, whether the day is holiday or not, whether the day is a workingday or not, the weather category, temperature, feeling temperature, humidity, and windspeed, as well as the interaction between feeling temperature and holiday.

<!-- ```{r} -->
<!-- cnt_full <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- tidy(cnt_full) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- cnt_full <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(cnt ~ season + yr + holiday + workingday + weathersit + -->
<!--         temperature_raw + feeling_temperature_raw + humidity_raw + -->
<!--         windspeed_raw + feeling_temperature_raw * holiday,  -->
<!--       data = dcbikeshare) -->
<!-- tidy(cnt_full) -->
<!-- ``` -->
Record adjusted R2 of the model.

<!-- ```{r} -->
<!-- glance(cnt_full)$adj.r.squared -->
<!-- ``` -->
[1] 0.8201774

Investigate how the model values change depending on whether a day is a holiday or not and answer the following questions.

Which of the following statements are correct?
The intercept for non-holidays is higher than for holidays ✓
The slope for temperature is different between the two models. ✗
The slope for feeling temperature is steeper for holidays than for non-holidays. ✓
The slope for feeling temperature is steeper for non-holidays than for holidays. ✗

According to this model, assuming everything else is the same, in which season does the model predict total daily bike rentals to be highest and which to be the lowest?

Select the correct answer
Highest: Spring, Lowest: Fall ✗
Highest: Fall, Lowest: Winter ✓
Highest: Spring, Lowest: Winter ✗
Highest: Fall, Lowest: Spring ✗
Highest: Summer, Lowest: Fall ✗
Highest: Summer, Lowest: Winter ✗

### Backward selection
Perform the first step of backward selection by fitting a series of models, each with one explanatory variable removed from the full model you fit in the previous exercise. Record the adjusted R2s of each of these models.

In the chunk below, fit the full model without the season variable and print out the R2 score.

<!-- ```{r} -->
<!-- rm_season <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->
<!-- ```{r} -->
<!-- rm_season <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(cnt ~ 1, data = dcbikeshare) -->
<!-- glance(cnt_full)$adj.r.squared -->
<!-- ``` -->
Error: object 'cnt_full' not found

In the chunk below, fit the full model without the year variable and print out the adjusted R2 score.

<!-- ```{r} -->
<!-- rm_year <- ___ %>% -->
<!--   ___ %>% -->
<!--   fit(cnt ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->

In the chunk below, fit the full model without the holiday variable and print out the adjusted R2 score. Remember to also remove the interaction effect between holiday and feeling_temperature_raw.

<!-- ```{r} -->
<!-- rm_holiday <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(rm_holiday)$adj.r.squared -->
<!-- ``` -->

Fit the full model without the workingday variable using the code chunk below! Remember to record the adjusted R2 score.

<!-- ```{r} -->
<!-- rm_workingday<- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->

Fit the full model without the weathersit variable in the chunk below and record the adjusted R2 score.

<!-- ```{r} -->
<!-- rm_weathersit<- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->

Remove the temperature_raw variable in the chunk below and record the adjusted R2 score.

<!-- ```{r} -->
<!-- rm_temp_raw<- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->

In the chunk below, fit the full model without the feeling_temperature_raw variable and record the adjusted R2 score. Don’t forget to also remove the interaction effect between holiday and feeling_temperature_raw!

<!-- ```{r} -->
<!-- rm_feeltemp_raw <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->

Fit the full model without the humidity_raw variable and record the adjusted R2 score.

<!-- ```{r} -->
<!-- rm_humidity_raw <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->

Fit the full model without the windspeed_raw variable and record the adjusted R2 score.

<!-- ```{r} -->
<!-- rm_windspeed_raw <- linear_reg() %>% -->
<!--   set_engine("lm") %>% -->
<!--   fit(___ ~ ___, data = ___) -->
<!-- glance(___)$___ -->
<!-- ``` -->
Last, remove the interaction effect between holiday and feeling_temperature_raw without removing the two variables individually. Then, record the adjusted R2.

<!-- # ```{r} -->
<!-- # rm_interaction <- linear_reg() %>% -->
<!-- #   set_engine("lm") %>% -->
<!-- #   fit(___ ~ ___, data = ___) -->
<!-- # glance(___)$___ -->
<!-- ``` -->
Now, using your findings from the previous exercises, answer the following question:

Which model of these models, if any, gives the highest improvement over the full model?
rm_season, rm_workingday, rm_year ✗
rm_season, rm_interaction, rm_holiday ✗
rm_winspeed_raw, rm_humidity_raw, rm_year ✗
rm_feeltemp_raw, rm_workingday, rm_interaction ✗
All ✗
None ✓

### Wrap up

Congratulations!

Hopefully, you have enjoyed this lesson on modelling and data wrangling.
